lint: clean
	pylint --rcfile=~/.pylint main.py netProbe sched hostId

clean:
	rm -f *pyc netProbe/*pyc sched/*pyc hostId/*pyc
	rm -f *~ netProbe/*~ sched/*~ hostId/*~ 

# git commit
# git push origin master
#
# git rm --cached %
# git add %
