#!/bin/sh
#
# Simple cron script - save the current clock periodically in case of
# a power failure or other crash

if (command -v fake-hwclock >/dev/null 2>&1) ; then

  # check wether / is mouonted RW => operation currently occuring
  mount | fgrep ext4 | fgrep ' / ' | fgrep rw > /dev/null
  if [ $? -eq 0 ]
  then
      fake-hwclock save
      exit
  fi

  mount -o remount,rw /
  fake-hwclock save
  mount -o remount,ro /
fi
